services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-dev
    restart: no
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-sal}
      DB_HOST: ${DB_HOST:-postgres-api}
    depends_on:
      - postgres-api
  postgres-api:
    image: postgres:17-alpine
    restart: no
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-sal}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
